### ISSUE TITLE
Note sure how to contribute this updated README & a conda yml file

### ISSUE THREAD

**Issue by Jim-Salmons** [ChWick/ocrgtannotator#2]
Hi Christoph @ChWick,

I know you are on the hotseat getting ready for #DATeCH2019 and I am an old Smalltalk developer so I have next to nil team source control skills or experience... so this is the best way I know to get a couple files to you in preparation for what I am sure will be a surge in interest in both #Calamari and #ocrGTannotator following the conference.

The updated README has additional instructions for prospective Windows developers including advice on creating the Windows symlinks that are handled automatically under other OSes. The README also has advice for alternative installation for Anaconda-based Python developers.

Note that I had to set both these attached files with the additional '.txt' filetype extension to upload here. The instructions in the README assume that the 'yml' file is in the same 'server' directory where the requirements.txt file is found.

[README.md.txt](https://github.com/ChWick/ocrgtannotator/files/3136002/README.md.txt)
[ocrgt.yml.txt](https://github.com/ChWick/ocrgtannotator/files/3136004/ocrgt.yml.txt)

**Comment by ChWick** [comment]
Thanks for the updates, I added them to the master branch!
